/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:11:35)
 */
package org.demo.orders.domain.service;

public interface DomainService {

    /**
     * Returns current domain model version
     * @return version
     */
    String getVersion() ;
}
