/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:15:28)
 */

package org.demo.orders.application.service;

import org.demo.orders.rest.dto.CatalogRestDto;

/**
 * Service for "COMMANDS" (database write operations)
 * Entity Catalog
 *
 * @author @{AUTHOR}
 */

public interface CatalogCommandService {

	/**
	 * Insert a new Catalog 
	 * @param catalogRestDto Data Transfer Object
	 * @return created aggregate
	 */
	public CatalogRestDto insertCatalog(CatalogRestDto catalogRestDto);

	/**
	 * Delete Catalog with the given id
	 * @param year id
	 * @param quarter id
	 */
	public void deleteCatalog(short year, short quarter);
	
	/**
	 * Save Catalog (update or create)
	 * @param year id
	 * @param quarter id
	 * @param catalogRestDto Data Transfer Object
	 * @return true if created (else false)
	 */
	public boolean saveCatalog(short year, short quarter, CatalogRestDto catalogRestDto);

}
