/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:15:28)
 */

package org.demo.orders.application.service;

import java.util.List;

import org.demo.orders.rest.dto.response.CatalogRestResponse;
//import org.demo.orders.domain.model.Catalog;
import org.demo.orders.rest.dto.CatalogRestDto;

/**
 * Service for "QUERIES" (database read operations)
 * Entity Catalog
 *
 * @author Telosys
 */
public interface CatalogQueryService {

	/**
	 * Get and return a Catalog instance for the given id
	 * @param year id
	 * @param quarter id
	 * @return entity found (or null if not found)
	 */
	public CatalogRestDto getCatalog(short year, short quarter);
	
	/**
	 * Get a page of Catalog 
	 * @param page page number (from 1 to N)
	 * @param size page size
	 * @param sort
	 * @param order
	 * @return
	 */
	 public CatalogRestResponse findCatalog(Integer page, Integer size, String sort, String order);

}
