/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:15:28)
 */

package org.demo.orders.application.service;

import org.demo.orders.rest.dto.CustomerRestDto;

/**
 * Service for "COMMANDS" (database write operations)
 * Entity Customer
 *
 * @author @{AUTHOR}
 */

public interface CustomerCommandService {

	/**
	 * Insert a new Customer 
	 * @param customerRestDto Data Transfer Object
	 * @return created aggregate
	 */
	public CustomerRestDto insertCustomer(CustomerRestDto customerRestDto);

	/**
	 * Delete Customer with the given id
	 * @param id id
	 */
	public void deleteCustomer(Integer id);
	
	/**
	 * Save Customer (update or create)
	 * @param id id
	 * @param customerRestDto Data Transfer Object
	 * @return true if created (else false)
	 */
	public boolean saveCustomer(Integer id, CustomerRestDto customerRestDto);

}
