/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:15:28)
 */

package org.demo.orders.application.service;

import java.util.List;

import org.demo.orders.rest.dto.response.CustomerRestResponse;
//import org.demo.orders.domain.model.Customer;
import org.demo.orders.rest.dto.CustomerRestDto;

/**
 * Service for "QUERIES" (database read operations)
 * Entity Customer
 *
 * @author Telosys
 */
public interface CustomerQueryService {

	/**
	 * Get and return a Customer instance for the given id
	 * @param id id
	 * @return entity found (or null if not found)
	 */
	public CustomerRestDto getCustomer(Integer id);
	
	/**
	 * Get a page of Customer 
	 * @param page page number (from 1 to N)
	 * @param size page size
	 * @param sort
	 * @param order
	 * @return
	 */
	 public CustomerRestResponse findCustomer(Integer page, Integer size, String sort, String order);

}
