/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:15:28)
 */

package org.demo.orders.application.service;

import org.demo.orders.rest.dto.OrderRestDto;

/**
 * Service for "COMMANDS" (database write operations)
 * Entity Order
 *
 * @author @{AUTHOR}
 */

public interface OrderCommandService {

	/**
	 * Insert a new Order 
	 * @param orderRestDto Data Transfer Object
	 * @return created aggregate
	 */
	public OrderRestDto insertOrder(OrderRestDto orderRestDto);

	/**
	 * Delete Order with the given id
	 * @param num id
	 */
	public void deleteOrder(Integer num);
	
	/**
	 * Save Order (update or create)
	 * @param num id
	 * @param orderRestDto Data Transfer Object
	 * @return true if created (else false)
	 */
	public boolean saveOrder(Integer num, OrderRestDto orderRestDto);

}
