/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:15:28)
 */

package org.demo.orders.application.service;

import java.util.List;

import org.demo.orders.rest.dto.response.OrderRestResponse;
//import org.demo.orders.domain.model.Order;
import org.demo.orders.rest.dto.OrderRestDto;

/**
 * Service for "QUERIES" (database read operations)
 * Entity Order
 *
 * @author Telosys
 */
public interface OrderQueryService {

	/**
	 * Get and return a Order instance for the given id
	 * @param num id
	 * @return entity found (or null if not found)
	 */
	public OrderRestDto getOrder(Integer num);
	
	/**
	 * Get a page of Order 
	 * @param page page number (from 1 to N)
	 * @param size page size
	 * @param sort
	 * @param order
	 * @return
	 */
	 public OrderRestResponse findOrder(Integer page, Integer size, String sort, String order);

}
