/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:15:28)
 */
package org.demo.orders.application.mapper;

import java.util.List; 
import org.mapstruct.Mapper;

import org.demo.orders.domain.model.Catalog;
import org.demo.orders.rest.dto.CatalogRestDto;
/**
 * Mapper for entity "Catalog" 
 * Conversion from domain object to DTO 
 * 
 * @author Telosys
 */
@Mapper(componentModel = "spring")
public interface CatalogMapper {

	/**
	 * Converts the given domain object to DTO
	 * @param catalog object to convert
	 * @return
	 */	
	public CatalogRestDto toDTO(Catalog catalog);
	
	/**
	 * Converts the given domain list to DTO list
	 * @param catalogList list to convert
	 * @return
	 */	
	public List<CatalogRestDto> toDTOList(List<Catalog> catalogList);

}

