/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:15:28)
 */
package org.demo.orders.application.mapper;

import java.util.List; 
import org.mapstruct.Mapper;

import org.demo.orders.domain.model.Category;
import org.demo.orders.rest.dto.CategoryRestDto;
/**
 * Mapper for entity "Category" 
 * Conversion from domain object to DTO 
 * 
 * @author Telosys
 */
@Mapper(componentModel = "spring")
public interface CategoryMapper {

	/**
	 * Converts the given domain object to DTO
	 * @param category object to convert
	 * @return
	 */	
	public CategoryRestDto toDTO(Category category);
	
	/**
	 * Converts the given domain list to DTO list
	 * @param categoryList list to convert
	 * @return
	 */	
	public List<CategoryRestDto> toDTOList(List<Category> categoryList);

}

