/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:15:28)
 */
package org.demo.orders.application.mapper;

import java.util.List; 
import org.mapstruct.Mapper;

import org.demo.orders.domain.model.DeliveryAddress;
import org.demo.orders.rest.dto.DeliveryAddressRestDto;
/**
 * Mapper for entity "DeliveryAddress" 
 * Conversion from domain object to DTO 
 * 
 * @author Telosys
 */
@Mapper(componentModel = "spring")
public interface DeliveryAddressMapper {

	/**
	 * Converts the given domain object to DTO
	 * @param deliveryAddress object to convert
	 * @return
	 */	
	public DeliveryAddressRestDto toDTO(DeliveryAddress deliveryAddress);
	
	/**
	 * Converts the given domain list to DTO list
	 * @param deliveryAddressList list to convert
	 * @return
	 */	
	public List<DeliveryAddressRestDto> toDTOList(List<DeliveryAddress> deliveryAddressList);

}

