/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:15:28)
 */
package org.demo.orders.application.mapper;

import java.util.List; 
import org.mapstruct.Mapper;

import org.demo.orders.domain.model.OrderItem;
import org.demo.orders.rest.dto.OrderItemRestDto;
/**
 * Mapper for entity "OrderItem" 
 * Conversion from domain object to DTO 
 * 
 * @author Telosys
 */
@Mapper(componentModel = "spring")
public interface OrderItemMapper {

	/**
	 * Converts the given domain object to DTO
	 * @param orderItem object to convert
	 * @return
	 */	
	public OrderItemRestDto toDTO(OrderItem orderItem);
	
	/**
	 * Converts the given domain list to DTO list
	 * @param orderItemList list to convert
	 * @return
	 */	
	public List<OrderItemRestDto> toDTOList(List<OrderItem> orderItemList);

}

