/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:15:28)
 */
package org.demo.orders.application.mapper;

import java.util.List; 
import org.mapstruct.Mapper;

import org.demo.orders.domain.model.Product;
import org.demo.orders.rest.dto.ProductRestDto;
/**
 * Mapper for entity "Product" 
 * Conversion from domain object to DTO 
 * 
 * @author Telosys
 */
@Mapper(componentModel = "spring", uses = { CategoryMapper.class })
public interface ProductMapper {

	/**
	 * Converts the given domain object to DTO
	 * @param product object to convert
	 * @return
	 */	
	public ProductRestDto toDTO(Product product);
	
	/**
	 * Converts the given domain list to DTO list
	 * @param productList list to convert
	 * @return
	 */	
	public List<ProductRestDto> toDTOList(List<Product> productList);

}

