/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:13:48)
 */
package org.demo.orders.rest.dto.common;

import java.util.LinkedList;
import java.util.List;

/**
 * Abstract class for REST response providing a page of DTO
 *
 * @author Telosys
 */
public abstract class AbstractRestResponse<T> {

    private final long totalElements ;
    private final int totalPages ;
    private final int pageSize ;
    private final List<T> list ;

    /**
     * Constructor
     * @param list
     * @param totalElements
     * @param pageSize
     */
    public AbstractRestResponse(List<T> list, long totalElements, int pageSize) {
        if ( list != null ) {
            this.list = list;
        }
        else {
            this.list = new LinkedList<>();
        }
        this.totalElements = totalElements ;
        this.pageSize = pageSize ;
        this.totalPages = numberOfPages(totalElements, pageSize);
    }

    /**
     * Calculates the number of pages available
     * @param numberOfElements
     * @param pageSize
     * @return
     */
    private int numberOfPages(long numberOfElements, int pageSize) {
        int pages = (int) numberOfElements / pageSize;
        int part  = (numberOfElements % pageSize == 0) ? 0 : 1;
        return pages + part;
    }

    /**
     * Returns the list of elements in the current page
     * @return
     */
    public List<T> getList() {
        return list;
    }

    /**
     * Returns the total of elements
     * @return
     */
    public long getTotalElements() {
        return totalElements;
    }

    /**
     * Returns the total of pages
     * @return
     */
    public int getTotalPages() {
        return totalPages;
    }
}
