/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:13:48)
 */
package org.demo.orders.rest.dto;

import java.io.Serializable;


/**
 * REST DTO for entity "Catalog"
 * 
 * @author Telosys
 *
 */
public class CatalogRestDto implements Serializable
{
    private static final long serialVersionUID = 1L;

    private short year; // ID
    private short quarter; // ID
    private String title; 


    /**
     * Default constructor
     */
    public CatalogRestDto() {
        super();
    }
    
    /**
     * Set the "year" field value
     * @param year
     */
	public void setYear( short year ) {
        this.year = year ;
    }
    /**
     * Get the "year" field value
     * @return the field value
     */
	public short getYear() {
        return this.year;
    }

    /**
     * Set the "quarter" field value
     * @param quarter
     */
	public void setQuarter( short quarter ) {
        this.quarter = quarter ;
    }
    /**
     * Get the "quarter" field value
     * @return the field value
     */
	public short getQuarter() {
        return this.quarter;
    }

    /**
     * Set the "title" field value
     * @param title
     */
	public void setTitle( String title ) {
        this.title = title ;
    }
    /**
     * Get the "title" field value
     * @return the field value
     */
	public String getTitle() {
        return this.title;
    }



    @Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(year);
        sb.append("|");
        sb.append(quarter);
        sb.append("|");
        sb.append(title);
        return sb.toString(); 
    } 

}
