/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:13:48)
 */
package org.demo.orders.rest.dto;

import java.io.Serializable;


/**
 * REST DTO for entity "Customer"
 * 
 * @author Telosys
 *
 */
public class CustomerRestDto implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer id; // ID
    private String firstName; 
    private String lastName; 

    //--- Relationships
    private CustomerAddressRestDto address ; 

    /**
     * Default constructor
     */
    public CustomerRestDto() {
        super();
    }
    
    /**
     * Set the "id" field value
     * @param id
     */
	public void setId( Integer id ) {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * @return the field value
     */
	public Integer getId() {
        return this.id;
    }

    /**
     * Set the "firstName" field value
     * @param firstName
     */
	public void setFirstName( String firstName ) {
        this.firstName = firstName ;
    }
    /**
     * Get the "firstName" field value
     * @return the field value
     */
	public String getFirstName() {
        return this.firstName;
    }

    /**
     * Set the "lastName" field value
     * @param lastName
     */
	public void setLastName( String lastName ) {
        this.lastName = lastName ;
    }
    /**
     * Get the "lastName" field value
     * @return the field value
     */
	public String getLastName() {
        return this.lastName;
    }


    //--- Relationships
    public CustomerAddressRestDto getAddress() {
        return this.address;
    } 
    public void setAddress(CustomerAddressRestDto address) {
        this.address = address;
    } 
	

    @Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(firstName);
        sb.append("|");
        sb.append(lastName);
        return sb.toString(); 
    } 

}
