/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:13:48)
 */
package org.demo.orders.rest.dto;

import java.io.Serializable;


/**
 * REST DTO for entity "DeliveryAddress"
 * 
 * @author Telosys
 *
 */
public class DeliveryAddressRestDto implements Serializable
{
    private static final long serialVersionUID = 1L;

    private int id; // ID
    private Integer orderNum; 
    private String street; 
    private String complement; 
    private String zipCode; 
    private String city; 
    private String state; 


    /**
     * Default constructor
     */
    public DeliveryAddressRestDto() {
        super();
    }
    
    /**
     * Set the "id" field value
     * @param id
     */
	public void setId( int id ) {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * @return the field value
     */
	public int getId() {
        return this.id;
    }

    /**
     * Set the "orderNum" field value
     * @param orderNum
     */
	public void setOrderNum( Integer orderNum ) {
        this.orderNum = orderNum ;
    }
    /**
     * Get the "orderNum" field value
     * @return the field value
     */
	public Integer getOrderNum() {
        return this.orderNum;
    }

    /**
     * Set the "street" field value
     * @param street
     */
	public void setStreet( String street ) {
        this.street = street ;
    }
    /**
     * Get the "street" field value
     * @return the field value
     */
	public String getStreet() {
        return this.street;
    }

    /**
     * Set the "complement" field value
     * @param complement
     */
	public void setComplement( String complement ) {
        this.complement = complement ;
    }
    /**
     * Get the "complement" field value
     * @return the field value
     */
	public String getComplement() {
        return this.complement;
    }

    /**
     * Set the "zipCode" field value
     * @param zipCode
     */
	public void setZipCode( String zipCode ) {
        this.zipCode = zipCode ;
    }
    /**
     * Get the "zipCode" field value
     * @return the field value
     */
	public String getZipCode() {
        return this.zipCode;
    }

    /**
     * Set the "city" field value
     * @param city
     */
	public void setCity( String city ) {
        this.city = city ;
    }
    /**
     * Get the "city" field value
     * @return the field value
     */
	public String getCity() {
        return this.city;
    }

    /**
     * Set the "state" field value
     * @param state
     */
	public void setState( String state ) {
        this.state = state ;
    }
    /**
     * Get the "state" field value
     * @return the field value
     */
	public String getState() {
        return this.state;
    }



    @Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(orderNum);
        sb.append("|");
        sb.append(street);
        sb.append("|");
        sb.append(complement);
        sb.append("|");
        sb.append(zipCode);
        sb.append("|");
        sb.append(city);
        sb.append("|");
        sb.append(state);
        return sb.toString(); 
    } 

}
