/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:11:35)
 */
package org.demo.orders.domain.service.impl;

import org.demo.orders.domain.service.DomainService;

public class DomainServiceImpl implements DomainService {
    private static final String VERSION = "1.0.0" ;

    @Override
    public String getVersion() {
        return VERSION;
    }
}