/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:12:15)
 */
package org.demo.orders.infra.mybatis.repository;

import java.util.List;

import javax.inject.Inject;

import org.springframework.stereotype.Repository;

import org.demo.orders.infra.mybatis.common.SqlRepository;
import org.demo.orders.infra.mybatis.common.SqlMapper;

import org.demo.orders.domain.model.Catalog;
import org.demo.orders.domain.model.CatalogId;
import org.demo.orders.domain.repository.CatalogRepository;

@Repository
public class CatalogSqlRepository extends SqlRepository<Catalog, CatalogId>
		implements CatalogRepository {

	@Inject
	private CatalogSqlMapper catalogSqlMapper;

	@Override
	protected SqlMapper<Catalog, CatalogId> getSqlMapper() {
		return catalogSqlMapper;
	}

	@Override
	protected void insertRelationship(final Catalog catalog) {
	}

	@Override
	protected void deleteRelationship(final Catalog catalog) {
	}

	// Add here specific methods if necessary 
/*
	@Override
	public List<Catalog> findAllByXxxx(Integer xxx, 
				Integer page, Integer size, String sort, String order){
		return catalogSqlMapper.findAllByXxxx(xxx, page * size, size,
				toSnakeCase(sort), order);
	}

	@Override
	public long countByXxxx(Integer xxx) {
		return catalogSqlMapper.countByXxxx(xxx);
	}
*/

}
