/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:12:15)
 */
package org.demo.orders.infra.mybatis.repository;

import java.util.List;

import javax.inject.Inject;

import org.springframework.stereotype.Repository;

import org.demo.orders.infra.mybatis.common.SqlRepository;
import org.demo.orders.infra.mybatis.common.SqlMapper;

import org.demo.orders.domain.model.Customer;
import org.demo.orders.domain.repository.CustomerRepository;

@Repository
public class CustomerSqlRepository extends SqlRepository<Customer, Integer>
		implements CustomerRepository {

	@Inject
	private CustomerSqlMapper customerSqlMapper;

	@Override
	protected SqlMapper<Customer, Integer> getSqlMapper() {
		return customerSqlMapper;
	}

	@Override
	protected void insertRelationship(final Customer customer) {
		// Link : address : CustomerAddress ( ManyToOne )
		// Link "many to one" not supposed to be inserted
	}

	@Override
	protected void deleteRelationship(final Customer customer) {
		// Link : address : CustomerAddress ( ManyToOne / OwningSide : true )
		// Link "many to one" not supposed to be deleted
	}

	// Add here specific methods if necessary 
/*
	@Override
	public List<Customer> findAllByXxxx(Integer xxx, 
				Integer page, Integer size, String sort, String order){
		return customerSqlMapper.findAllByXxxx(xxx, page * size, size,
				toSnakeCase(sort), order);
	}

	@Override
	public long countByXxxx(Integer xxx) {
		return customerSqlMapper.countByXxxx(xxx);
	}
*/

}
