/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:12:15)
 */
package org.demo.orders.infra.mybatis.repository;

import java.util.List;

import javax.inject.Inject;

import org.springframework.stereotype.Repository;

import org.demo.orders.infra.mybatis.common.SqlRepository;
import org.demo.orders.infra.mybatis.common.SqlMapper;

import org.demo.orders.domain.model.Order;
import org.demo.orders.domain.repository.OrderRepository;

@Repository
public class OrderSqlRepository extends SqlRepository<Order, Integer>
		implements OrderRepository {

	@Inject
	private OrderSqlMapper orderSqlMapper;

	@Override
	protected SqlMapper<Order, Integer> getSqlMapper() {
		return orderSqlMapper;
	}

	@Override
	protected void insertRelationship(final Order order) {
		// Link : items : List<OrderItem> ( OneToMany )
		orderSqlMapper.insertOrderItemList(order.getItems());
		// Link : deliveryAddress : DeliveryAddress ( ManyToOne )
		// Link "many to one" not supposed to be inserted
	}

	@Override
	protected void deleteRelationship(final Order order) {
		// Link : items : List<OrderItem> ( OneToMany / OwningSide : false )
		orderSqlMapper.deleteOrderItemList(order.getNum());
		// Link : deliveryAddress : DeliveryAddress ( ManyToOne / OwningSide : true )
		// Link "many to one" not supposed to be deleted
	}

	// Add here specific methods if necessary 
/*
	@Override
	public List<Order> findAllByXxxx(Integer xxx, 
				Integer page, Integer size, String sort, String order){
		return orderSqlMapper.findAllByXxxx(xxx, page * size, size,
				toSnakeCase(sort), order);
	}

	@Override
	public long countByXxxx(Integer xxx) {
		return orderSqlMapper.countByXxxx(xxx);
	}
*/

}
