/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:11:34)
 */
package org.demo.orders.domain.model;

import java.io.Serializable;


/**
 * Composite primary key for entity "Catalog"
 *
 * @author Telosys
 *
 */
public class CatalogId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private final short      year ;
    
    private final short      quarter ;
    

    /**
     * Constructor with values
     * @param year 
     * @param quarter 
     */
    public CatalogId( Short year, Short quarter ) {
        super();
		// TODO : check not null
        this.year = year ;
        this.quarter = quarter ;
    }
    
    //--- GETTERS & SETTERS FOR KEY FIELDS

    public short getYear() {
        return this.year;
    }


    public short getQuarter() {
        return this.quarter;
    }


    //--- equals METHOD
	@Override
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		CatalogId other = (CatalogId) obj; 
		//--- Attribute year
		if ( year != other.year ) return false ; 
		//--- Attribute quarter
		if ( quarter != other.quarter ) return false ; 
		return true; 
	} 

    //--- hashCode METHOD
	@Override
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute year
		result = prime * result + year;
		//--- Attribute quarter
		result = prime * result + quarter;
		
		return result; 
	} 

    //--- toString METHOD
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(year);
        sb.append("|");
        sb.append(quarter);
        return sb.toString(); 
    } 

}