/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:11:34)
 */
package org.demo.orders.domain.model;


/**
 * Domain class for "Catalog"
 *
 * @author Telosys
 *
 */
public final class Catalog extends CatalogParent {

	/**
	 * Constructor 
	 * @param year
	 * @param quarter
	 * @param title
	 */
	Catalog(
            short year,
            short quarter,
            String title
            ) {
        super(
		    year,		
		    quarter,		
		    title		
            );
	}


	/**
	 * Create aggregate business methods here...
	 */
	public void doSomethingWithThisAggregate() {
		// TODO
	}
}
