/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:11:34)
 */

package org.demo.orders.domain.model;

import org.demo.orders.domain.common.AggregateRoot;

/**
 * Domain parent abstract class for entity "Catalog"
 *
 * @author Telosys
 *
 */
public abstract class CatalogParent extends AggregateRoot {

	private short year;
	private short quarter;
	private String title;

	/**
	 * No default constructor 
	 * Default constructor is forbidden (explicitly private)
	 */
	private CatalogParent() {
	}

	/**
	 * Constructor 
	 * @param year
	 * @param quarter
	 * @param title
	 */
	CatalogParent(
                short year,
                short quarter,
                String title
                ) {
		this.year = year;
		this.quarter = quarter;
		this.title = title;
	}

    /**
     * Get the "year" attribute value
     * @return the attribute value
     */
	public short getYear() {
        return this.year;
    }

    /**
     * Get the "quarter" attribute value
     * @return the attribute value
     */
	public short getQuarter() {
        return this.quarter;
    }

    /**
     * Get the "title" attribute value
     * @return the attribute value
     */
	public String getTitle() {
        return this.title;
    }


	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(year);
        sb.append("|");
        sb.append(quarter);
        sb.append("|");
        sb.append(title);
        return sb.toString(); 
    } 

}
