/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:11:34)
 */
package org.demo.orders.domain.model;

import org.demo.orders.domain.common.Entity;

/**
 * Domain parent abstract class for entity "Category"
 *
 * @author Telosys
 *
 */
public abstract class CategoryParent extends Entity {

	private short code;
	private String name;

	/**
	 * No default constructor 
	 * Default constructor is forbidden (explicitly private)
	 */
	private CategoryParent() {
	}

	/**
	 * Constructor 
	 * @param code
	 * @param name
	 */
	CategoryParent(
                short code,
                String name
                ) {
		this.code = code;
		this.name = name;
	}

    /**
     * Get the "code" attribute value
     * @return the attribute value
     */
	public short getCode() {
        return this.code;
    }

    /**
     * Get the "name" attribute value
     * @return the attribute value
     */
	public String getName() {
        return this.name;
    }


	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(code);
        sb.append("|");
        sb.append(name);
        return sb.toString(); 
    } 

}
