/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:11:34)
 */
package org.demo.orders.domain.model;


/**
 * Domain class for "Category"
 *
 * @author Telosys
 *
 */
public final class Category extends CategoryParent {

	/**
	 * Constructor 
	 * @param code
	 * @param name
	 */
	Category(
            short code,
            String name
            ) {
        super(
		    code,		
		    name		
            );
	}


	/**
	 * Create aggregate business methods here...
	 */
	public void doSomethingWithThisAggregate() {
		// TODO
	}
}
