/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:11:34)
 */
package org.demo.orders.domain.model;


/**
 * Domain class for "CustomerAddress"
 *
 * @author Telosys
 *
 */
public final class CustomerAddress extends CustomerAddressParent {

	/**
	 * Constructor 
	 * @param id
	 * @param street
	 * @param complement
	 * @param zipCode
	 * @param city
	 * @param state
	 * @param customerId
	 */
	CustomerAddress(
            int id,
            String street,
            String complement,
            String zipCode,
            String city,
            String state,
            Integer customerId
            ) {
        super(
		    id,		
		    street,		
		    complement,		
		    zipCode,		
		    city,		
		    state,		
		    customerId		
            );
	}


	/**
	 * Create aggregate business methods here...
	 */
	public void doSomethingWithThisAggregate() {
		// TODO
	}
}
