/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:11:34)
 */
package org.demo.orders.domain.model;

import org.demo.orders.domain.common.AggregateRoot;

/**
 * Domain parent abstract class for entity "Customer"
 *
 * @author Telosys
 *
 */
public abstract class CustomerParent extends AggregateRoot {

	private Integer id;
	private String firstName;
	private String lastName;

    private CustomerAddress address ;
	/**
	 * No default constructor 
	 * Default constructor is forbidden (explicitly private)
	 */
	private CustomerParent() {
	}

	/**
	 * Constructor 
	 * @param id
	 * @param firstName
	 * @param lastName
	 * @param address
	 */
	CustomerParent(
                Integer id,
                String firstName,
                String lastName,
                CustomerAddress address
                ) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
        this.address = address;
	}

    /**
     * Get the "id" attribute value
     * @return the attribute value
     */
	public Integer getId() {
        return this.id;
    }

    /**
     * Get the "firstName" attribute value
     * @return the attribute value
     */
	public String getFirstName() {
        return this.firstName;
    }

    /**
     * Get the "lastName" attribute value
     * @return the attribute value
     */
	public String getLastName() {
        return this.lastName;
    }


	/**
     * Get the "address" 
     * @return
     */
    public CustomerAddress getAddress() {
        return this.address;
    } 

	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(firstName);
        sb.append("|");
        sb.append(lastName);
        return sb.toString(); 
    } 

}
