/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:11:34)
 */
package org.demo.orders.domain.model;


/**
 * Domain class for "DeliveryAddress"
 *
 * @author Telosys
 *
 */
public final class DeliveryAddress extends DeliveryAddressParent {

	/**
	 * Constructor 
	 * @param id
	 * @param orderNum
	 * @param street
	 * @param complement
	 * @param zipCode
	 * @param city
	 * @param state
	 */
	DeliveryAddress(
            int id,
            Integer orderNum,
            String street,
            String complement,
            String zipCode,
            String city,
            String state
            ) {
        super(
		    id,		
		    orderNum,		
		    street,		
		    complement,		
		    zipCode,		
		    city,		
		    state		
            );
	}


	/**
	 * Create aggregate business methods here...
	 */
	public void doSomethingWithThisAggregate() {
		// TODO
	}
}
