/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:11:34)
 */
package org.demo.orders.domain.model;

import org.demo.orders.domain.common.Entity;

/**
 * Domain parent abstract class for entity "DeliveryAddress"
 *
 * @author Telosys
 *
 */
public abstract class DeliveryAddressParent extends Entity {

	private int id;
	private Integer orderNum;
	private String street;
	private String complement;
	private String zipCode;
	private String city;
	private String state;

	/**
	 * No default constructor 
	 * Default constructor is forbidden (explicitly private)
	 */
	private DeliveryAddressParent() {
	}

	/**
	 * Constructor 
	 * @param id
	 * @param orderNum
	 * @param street
	 * @param complement
	 * @param zipCode
	 * @param city
	 * @param state
	 */
	DeliveryAddressParent(
                int id,
                Integer orderNum,
                String street,
                String complement,
                String zipCode,
                String city,
                String state
                ) {
		this.id = id;
		this.orderNum = orderNum;
		this.street = street;
		this.complement = complement;
		this.zipCode = zipCode;
		this.city = city;
		this.state = state;
	}

    /**
     * Get the "id" attribute value
     * @return the attribute value
     */
	public int getId() {
        return this.id;
    }

    /**
     * Get the "orderNum" attribute value
     * @return the attribute value
     */
	public Integer getOrderNum() {
        return this.orderNum;
    }

    /**
     * Get the "street" attribute value
     * @return the attribute value
     */
	public String getStreet() {
        return this.street;
    }

    /**
     * Get the "complement" attribute value
     * @return the attribute value
     */
	public String getComplement() {
        return this.complement;
    }

    /**
     * Get the "zipCode" attribute value
     * @return the attribute value
     */
	public String getZipCode() {
        return this.zipCode;
    }

    /**
     * Get the "city" attribute value
     * @return the attribute value
     */
	public String getCity() {
        return this.city;
    }

    /**
     * Get the "state" attribute value
     * @return the attribute value
     */
	public String getState() {
        return this.state;
    }


	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(orderNum);
        sb.append("|");
        sb.append(street);
        sb.append("|");
        sb.append(complement);
        sb.append("|");
        sb.append(zipCode);
        sb.append("|");
        sb.append(city);
        sb.append("|");
        sb.append(state);
        return sb.toString(); 
    } 

}
