/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:13:48)
 */
package org.demo.orders.domain.model;

import java.util.ArrayList;
import java.util.List;
import org.demo.orders.rest.dto.OrderRestDto;
import org.demo.orders.rest.dto.OrderItemRestDto;
import org.demo.orders.rest.dto.DeliveryAddressRestDto;
/**
 * Domain factory for aggregate "Order" 
 * based on REST DTO input
 *
 * @author Telosys
 */
//-----------------------------------
// referencesInDepth : 
// - OrderItem : 
//    . toOne  : false 
//    . toMany : true 
// - DeliveryAddress : 
//    . toOne  : true 
//    . toMany : false 
public final class OrderFactoryRestDto {

	/**
	 * Create a new instance of "Order" from "Data Transfer Object"
	 * @param dto the DTO 
	 * @return created instance
	 */

	public static Order createOrder(OrderRestDto dto) {
		if (dto == null) {
			throw new IllegalArgumentException("OrderRestDto is null");
		}
//		Order order = new Order(
		return new Order(
			dto.getNum(),
			dto.getOrderDate(),
			dto.getStatus(),
			dto.getComment(),
			dto.getCustomerId(),
			createOrderItemList(dto.getItems()),
			createDeliveryAddress(dto.getDeliveryAddress())
			);	
//		return order;
	}
	private static OrderItem createOrderItem(OrderItemRestDto dto) {
		if (dto == null) {
			throw new IllegalArgumentException("OrderItemRestDto is null");
		}
//		OrderItem orderItem = new OrderItem(
		return new OrderItem(
			dto.getId(),
			dto.getOrderNum(),
			dto.getProductCode(),
			dto.getQuantity(),
			dto.getUnitPrice(),
			dto.getDiscount(),
			dto.getComment()
			);	
//		return orderItem;
	}
	private static List<OrderItem> createOrderItemList(List<OrderItemRestDto> dtoList) {
		List<OrderItem> list = null;
		if (dtoList != null) {
			list = new ArrayList<>();
			for ( OrderItemRestDto dto : dtoList ) {
				list.add(createOrderItem(dto));
			}
		}
		return list;
	}
	private static DeliveryAddress createDeliveryAddress(DeliveryAddressRestDto dto) {
		if (dto == null) {
			throw new IllegalArgumentException("DeliveryAddressRestDto is null");
		}
//		DeliveryAddress deliveryAddress = new DeliveryAddress(
		return new DeliveryAddress(
			dto.getId(),
			dto.getOrderNum(),
			dto.getStreet(),
			dto.getComplement(),
			dto.getZipCode(),
			dto.getCity(),
			dto.getState()
			);	
//		return deliveryAddress;
	}
}
