/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:11:35)
 */
package org.demo.orders.domain.model;

import java.math.BigDecimal;
import org.demo.orders.domain.common.Entity;

/**
 * Domain parent abstract class for entity "OrderItem"
 *
 * @author Telosys
 *
 */
public abstract class OrderItemParent extends Entity {

	private long id;
	private Integer orderNum;
	private String productCode;
	private short quantity;
	private BigDecimal unitPrice;
	private BigDecimal discount;
	private String comment;

	/**
	 * No default constructor 
	 * Default constructor is forbidden (explicitly private)
	 */
	private OrderItemParent() {
	}

	/**
	 * Constructor 
	 * @param id
	 * @param orderNum
	 * @param productCode
	 * @param quantity
	 * @param unitPrice
	 * @param discount
	 * @param comment
	 */
	OrderItemParent(
                long id,
                Integer orderNum,
                String productCode,
                short quantity,
                BigDecimal unitPrice,
                BigDecimal discount,
                String comment
                ) {
		this.id = id;
		this.orderNum = orderNum;
		this.productCode = productCode;
		this.quantity = quantity;
		this.unitPrice = unitPrice;
		this.discount = discount;
		this.comment = comment;
	}

    /**
     * Get the "id" attribute value
     * @return the attribute value
     */
	public long getId() {
        return this.id;
    }

    /**
     * Get the "orderNum" attribute value
     * @return the attribute value
     */
	public Integer getOrderNum() {
        return this.orderNum;
    }

    /**
     * Get the "productCode" attribute value
     * @return the attribute value
     */
	public String getProductCode() {
        return this.productCode;
    }

    /**
     * Get the "quantity" attribute value
     * @return the attribute value
     */
	public short getQuantity() {
        return this.quantity;
    }

    /**
     * Get the "unitPrice" attribute value
     * @return the attribute value
     */
	public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }

    /**
     * Get the "discount" attribute value
     * @return the attribute value
     */
	public BigDecimal getDiscount() {
        return this.discount;
    }

    /**
     * Get the "comment" attribute value
     * @return the attribute value
     */
	public String getComment() {
        return this.comment;
    }


	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(orderNum);
        sb.append("|");
        sb.append(productCode);
        sb.append("|");
        sb.append(quantity);
        sb.append("|");
        sb.append(unitPrice);
        sb.append("|");
        sb.append(discount);
        sb.append("|");
        sb.append(comment);
        return sb.toString(); 
    } 

}
