/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:11:35)
 */
package org.demo.orders.domain.model;

import java.math.BigDecimal;

/**
 * Domain class for "OrderItem"
 *
 * @author Telosys
 *
 */
public final class OrderItem extends OrderItemParent {

	/**
	 * Constructor 
	 * @param id
	 * @param orderNum
	 * @param productCode
	 * @param quantity
	 * @param unitPrice
	 * @param discount
	 * @param comment
	 */
	OrderItem(
            long id,
            Integer orderNum,
            String productCode,
            short quantity,
            BigDecimal unitPrice,
            BigDecimal discount,
            String comment
            ) {
        super(
		    id,		
		    orderNum,		
		    productCode,		
		    quantity,		
		    unitPrice,		
		    discount,		
		    comment		
            );
	}


	/**
	 * Create aggregate business methods here...
	 */
	public void doSomethingWithThisAggregate() {
		// TODO
	}
}
