/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:11:35)
 */
package org.demo.orders.domain.model;

import java.math.BigDecimal;

/**
 * Domain class for "Product"
 *
 * @author Telosys
 *
 */
public final class Product extends ProductParent {

	/**
	 * Constructor 
	 * @param code
	 * @param name
	 * @param description
	 * @param unitPrice
	 * @param inStock
	 * @param activeForSale
	 * @param categoryId
	 * @param catalogYear
	 * @param catalogQuarter
	 * @param category
	 */
	Product(
            String code,
            String name,
            String description,
            BigDecimal unitPrice,
            Boolean inStock,
            Boolean activeForSale,
            Short categoryId,
            Short catalogYear,
            Short catalogQuarter,
            Category category
            ) {
        super(
		    code,		
		    name,		
		    description,		
		    unitPrice,		
		    inStock,		
		    activeForSale,		
		    categoryId,		
		    catalogYear,		
		    catalogQuarter,		
            category		
            );
	}


	/**
	 * Create aggregate business methods here...
	 */
	public void doSomethingWithThisAggregate() {
		// TODO
	}
}
