/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:13:48)
 */
package org.demo.orders.domain.model;

import java.util.ArrayList;
import java.util.List;
import org.demo.orders.rest.dto.ProductRestDto;
import org.demo.orders.rest.dto.CategoryRestDto;
/**
 * Domain factory for aggregate "Product" 
 * based on REST DTO input
 *
 * @author Telosys
 */
//-----------------------------------
// referencesInDepth : 
// - Category : 
//    . toOne  : true 
//    . toMany : false 
public final class ProductFactoryRestDto {

	/**
	 * Create a new instance of "Product" from "Data Transfer Object"
	 * @param dto the DTO 
	 * @return created instance
	 */

	public static Product createProduct(ProductRestDto dto) {
		if (dto == null) {
			throw new IllegalArgumentException("ProductRestDto is null");
		}
//		Product product = new Product(
		return new Product(
			dto.getCode(),
			dto.getName(),
			dto.getDescription(),
			dto.getUnitPrice(),
			dto.getInStock(),
			dto.getActiveForSale(),
			dto.getCategoryId(),
			dto.getCatalogYear(),
			dto.getCatalogQuarter(),
			createCategory(dto.getCategory())
			);	
//		return product;
	}
	private static Category createCategory(CategoryRestDto dto) {
		if (dto == null) {
			throw new IllegalArgumentException("CategoryRestDto is null");
		}
//		Category category = new Category(
		return new Category(
			dto.getCode(),
			dto.getName()
			);	
//		return category;
	}
}
