/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:11:34)
 */
package org.demo.orders.domain.repository;

import java.util.List;

import org.demo.orders.domain.common.AggregateRootRepository;

import org.demo.orders.domain.model.Catalog;
import org.demo.orders.domain.model.CatalogId;

public interface CatalogRepository extends AggregateRootRepository<Catalog, CatalogId> {

	// Add here any specific methods if necessary 'findByXxx' et 'countByXxxx' 
/*
	Examples :
	
	List<Catalog> findByXxx(Integer xxx);


	long countByXxx(Integer xxx);
*/
}
