/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:11:34)
 */
package org.demo.orders.domain.repository;

import java.util.List;

import org.demo.orders.domain.common.AggregateRootRepository;

import org.demo.orders.domain.model.Customer;

public interface CustomerRepository extends AggregateRootRepository<Customer, Integer> {

	// Add here any specific methods if necessary 'findByXxx' et 'countByXxxx' 
/*
	Examples :
	
	List<Customer> findByXxx(Integer xxx);


	long countByXxx(Integer xxx);
*/
}
