/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:11:35)
 */
package org.demo.orders.domain.repository;

import java.util.List;

import org.demo.orders.domain.common.AggregateRootRepository;

import org.demo.orders.domain.model.Order;

public interface OrderRepository extends AggregateRootRepository<Order, Integer> {

	// Add here any specific methods if necessary 'findByXxx' et 'countByXxxx' 
/*
	Examples :
	
	List<Order> findByXxx(Integer xxx);


	long countByXxx(Integer xxx);
*/
}
