/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:11:35)
 */
package org.demo.orders.domain.common;

/**
 * Ancestor for domain model "aggregate root" entities
 *
 * @author Telosys
 *
 */
public abstract class AggregateRoot extends Entity {

}