/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:11:35)
 */
package org.demo.orders.domain.common;

/**
 * Repository standard interface for "aggregate root" entities
 *
 * @author Telosys
 *
 */

import java.util.List;
import java.util.Optional;

public interface AggregateRootRepository<T extends AggregateRoot, ID> {

	/**
	 * Finds an entity for the given id
	 * @param id
	 * @return
	 */
	Optional<T> findById(ID id);

	/**
	 * Finds all existing entities with pagination and sorting
	 * @param page
	 * @param size
	 * @param sort
	 * @param order
	 * @return
	 */
	List<T> findAll(Integer page, Integer size, String sort, String order);

	/**
	 * Counts all existing entities 
	 * @return
	 */
	long count();

	/**
	 * Inserts the given entity in the database (SQL INSERT)
	 * @param entity
	 * @return number of inserted rows (0 or 1)
	 */
	int insert(T entity);

	/**
	 * Updates the given entity in the database if it exists (SQL UPDATE)
	 * @param entity
	 * @return number of updated rows (0 or 1)
	 */
	int update(final T entity);

	/**
	 * Deletes the given entity in the database if it exists (SQL DELETE)
	 * @param entity
	 * @return number of deleted rows (0 or 1)
	 */
	int delete(T entity);

}
