/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:15:28)
 */

package org.demo.orders.rest.api;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Response;

import org.demo.orders.rest.dto.CatalogRestDto;

/**
 * REST API interface for Catalog
 * 
 * @author Telosys
 */
@Path("/catalog")
public interface CatalogRestApi {

    @GET
    @Path("/{year}/{quarter}")
    @Produces({ "application/json" })	
    Response getCatalog(@PathParam("year") short year, @PathParam("quarter") short quarter);

    @GET
    @Path("/")
    @Produces({ "application/json" })	
    Response findCatalog(@QueryParam("page") Integer page, @QueryParam("size") Integer size,
            @QueryParam("sort") String sort, @QueryParam("order") String order);

    @POST
    @Path("/")
    @Consumes({ "application/json" })
	Response insertCatalog(CatalogRestDto catalogRestDto);

    @PUT	
    @Path("/{year}/{quarter}")
    @Consumes({ "application/json" })
    Response updateCatalog(@PathParam("year") short year, @PathParam("quarter") short quarter,
            CatalogRestDto catalogRestDto);

	@DELETE
    @Path("/{year}/{quarter}")
    Response deleteCatalog(@PathParam("year") short year, @PathParam("quarter") short quarter);
}