/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:15:28)
 */

package org.demo.orders.rest.api;

import javax.ws.rs.*;
import javax.ws.rs.core.Response;

import org.demo.orders.rest.dto.CustomerRestDto;

/**
 * REST API interface for Customer
 * 
 * @author Telosys
 */
@Path("/customer")
public interface CustomerRestApi {

    @GET
    @Path("/{id}")
    @Produces({ "application/json" })	
	Response getCustomer(Integer id);

    @GET
    @Path("/")
    @Produces({ "application/json" })	
	Response findCustomer(Integer page, Integer size, String sort, String order);

    @POST
    @Path("/")
    @Consumes({ "application/json" })
	Response insertCustomer(CustomerRestDto customerRestDto);

    @PUT	
    @Path("/")
    @Consumes({ "application/json" })
	Response updateCustomer(Integer id, CustomerRestDto customerRestDto);		

	@DELETE
    @Path("/{id}")
	Response deleteCustomer(Integer id);
}