/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:15:28)
 */

package org.demo.orders.rest.api;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Response;

import org.demo.orders.rest.dto.CustomerRestDto;

/**
 * REST API interface for Customer
 * 
 * @author Telosys
 */
@Path("/customer")
public interface CustomerRestApi {

    @GET
    @Path("/{id}")
    @Produces({ "application/json" })	
    Response getCustomer(@PathParam("id") Integer id);

    @GET
    @Path("/")
    @Produces({ "application/json" })	
    Response findCustomer(@QueryParam("page") Integer page, @QueryParam("size") Integer size,
            @QueryParam("sort") String sort, @QueryParam("order") String order);

    @POST
    @Path("/")
    @Consumes({ "application/json" })
	Response insertCustomer(CustomerRestDto customerRestDto);

    @PUT	
    @Path("/{id}")
    @Consumes({ "application/json" })
    Response updateCustomer(@PathParam("id") Integer id, CustomerRestDto customerRestDto);

	@DELETE
    @Path("/{id}")
    Response deleteCustomer(@PathParam("id") Integer id);
}