/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:15:28)
 */

package org.demo.orders.rest.api;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Response;

import org.demo.orders.rest.dto.OrderRestDto;

/**
 * REST API interface for Order
 * 
 * @author Telosys
 */
@Path("/order")
public interface OrderRestApi {

    @GET
    @Path("/{num}")
    @Produces({ "application/json" })	
    Response getOrder(@PathParam("num") Integer num);

    @GET
    @Path("/")
    @Produces({ "application/json" })	
    Response findOrder(@QueryParam("page") Integer page, @QueryParam("size") Integer size,
            @QueryParam("sort") String sort, @QueryParam("order") String order);

    @POST
    @Path("/")
    @Consumes({ "application/json" })
	Response insertOrder(OrderRestDto orderRestDto);

    @PUT	
    @Path("/{num}")
    @Consumes({ "application/json" })
    Response updateOrder(@PathParam("num") Integer num, OrderRestDto orderRestDto);

	@DELETE
    @Path("/{num}")
    Response deleteOrder(@PathParam("num") Integer num);
}