/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:15:28)
 */

package org.demo.orders.rest.api;

import javax.ws.rs.*;
import javax.ws.rs.core.Response;

import org.demo.orders.rest.dto.OrderRestDto;

/**
 * REST API interface for Order
 * 
 * @author Telosys
 */
@Path("/order")
public interface OrderRestApi {

    @GET
    @Path("/{num}")
    @Produces({ "application/json" })	
	Response getOrder(Integer num);

    @GET
    @Path("/")
    @Produces({ "application/json" })	
	Response findOrder(Integer page, Integer size, String sort, String order);

    @POST
    @Path("/")
    @Consumes({ "application/json" })
	Response insertOrder(OrderRestDto orderRestDto);

    @PUT	
    @Path("/")
    @Consumes({ "application/json" })
	Response updateOrder(Integer num, OrderRestDto orderRestDto);		

	@DELETE
    @Path("/{num}")
	Response deleteOrder(Integer num);
}