/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:15:28)
 */

package org.demo.orders.rest.api;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Response;

import org.demo.orders.rest.dto.ProductRestDto;

/**
 * REST API interface for Product
 * 
 * @author Telosys
 */
@Path("/product")
public interface ProductRestApi {

    @GET
    @Path("/{code}")
    @Produces({ "application/json" })	
    Response getProduct(@PathParam("code") String code);

    @GET
    @Path("/")
    @Produces({ "application/json" })	
    Response findProduct(@QueryParam("page") Integer page, @QueryParam("size") Integer size,
            @QueryParam("sort") String sort, @QueryParam("order") String order);

    @POST
    @Path("/")
    @Consumes({ "application/json" })
	Response insertProduct(ProductRestDto productRestDto);

    @PUT	
    @Path("/{code}")
    @Consumes({ "application/json" })
    Response updateProduct(@PathParam("code") String code, ProductRestDto productRestDto);

	@DELETE
    @Path("/{code}")
    Response deleteProduct(@PathParam("code") String code);
}