/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:15:28)
 */

package org.demo.orders.rest.api;

import javax.ws.rs.*;
import javax.ws.rs.core.Response;

import org.demo.orders.rest.dto.ProductRestDto;

/**
 * REST API interface for Product
 * 
 * @author Telosys
 */
@Path("/product")
public interface ProductRestApi {

    @GET
    @Path("/{code}")
    @Produces({ "application/json" })	
	Response getProduct(String code);

    @GET
    @Path("/")
    @Produces({ "application/json" })	
	Response findProduct(Integer page, Integer size, String sort, String order);

    @POST
    @Path("/")
    @Consumes({ "application/json" })
	Response insertProduct(ProductRestDto productRestDto);

    @PUT	
    @Path("/")
    @Consumes({ "application/json" })
	Response updateProduct(String code, ProductRestDto productRestDto);		

	@DELETE
    @Path("/{code}")
	Response deleteProduct(String code);
}