-- DROP TABLES
-- Generated by Telosys ( https://www.telosys.org/ )
-- 2022-04-12 (15:13:08)
DROP TABLE "catalog" CASCADE ;
DROP TABLE "category" CASCADE ;
DROP TABLE "customer" CASCADE ;
DROP TABLE "customer_address" CASCADE ;
DROP TABLE "delivery_address" CASCADE ;
DROP TABLE "order" CASCADE ;
DROP TABLE "order_item" CASCADE ;
DROP TABLE "product" CASCADE ;
