/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-12 (15:15:28)
 */

package org.demo.orders.rest.api.impl;

import javax.inject.Inject;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.UriBuilder;

import org.springframework.web.bind.annotation.RestController;

import org.demo.orders.rest.common.AbstractController;
import org.demo.orders.rest.api.CatalogRestApi;
import org.demo.orders.rest.dto.CatalogRestDto;


import org.demo.orders.application.service.CatalogQueryService;
import org.demo.orders.application.service.CatalogCommandService;

@RestController
public class CatalogRestController extends AbstractController implements CatalogRestApi {

 
	@Inject
	private CatalogQueryService catalogQueryService;

	@Inject
	private CatalogCommandService catalogCommandService;


	@Override
	public Response getCatalog(short year, short quarter) {
		return Response.ok(catalogQueryService.getCatalog(year, quarter)).build();
	}

	@Override
	public Response findCatalog(Integer page, Integer size, String sort, String order) {
		return Response.ok(catalogQueryService.findCatalog(page, size, sort, order)).build();
	}


	@Override
	public Response insertCatalog(CatalogRestDto catalogRestDto) {
		CatalogRestDto inserted = catalogCommandService.insertCatalog(catalogRestDto);

		UriBuilder uriBuilder = uriInfo.getAbsolutePathBuilder();

		uriBuilder.path(String.valueOf(inserted.getYear()));
		uriBuilder.path(String.valueOf(inserted.getQuarter()));
        return Response.created(uriBuilder.build()).build();
	}

	@Override
	public Response updateCatalog(short year, short quarter, CatalogRestDto catalogRestDto) {		
		boolean created = catalogCommandService.saveCatalog(year, quarter, catalogRestDto);
		if (created) {
			return Response.created(uriInfo.getAbsolutePathBuilder().build()).build();
		} else {
			return Response.ok().build();
		}
	}

	@Override
	public Response deleteCatalog(short year, short quarter) {
		catalogCommandService.deleteCatalog(year, quarter);
		return Response.ok().build();
	}

}